spring:
  profiles:
      active: dev
  datasource:
    oldDataBase:
      jdbc-url: jdbc:mysql://localhost:3306/nationalOld?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: root
      password: zh94061011
    newDataBase:
      jdbc-url: jdbc:mysql://localhost:3306/nationalNew?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: root
      password: zh94061011