spring:
  profiles:
      active: dev
  datasource:
    old:
        url: jdbc:mysql://localhost:3306/1.0Data?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: zh94061011
        driver-class-name: com.mysql.jdbc.Driver
    new:
        url: jdbc:mysql://localhost:3306/2.0data?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: zh94061011
        driver-class-name: com.mysql.jdbc.Driver
    server:
        url: jdbc:mysql://localhost:3306/national_service?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: zh94061011
        driver-class-name: com.mysql.jdbc.Driver

  jpa:
      properties:
        hibernate:
#          show_sql: true
          format_sql: true
server:
  port: 8888

#    oldDataBase:
#      jdbc-url: jdbc:mysql://localhost:3306/nationalOld?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#      username: root
#      password: zh94061011
