spring:
  profiles:
      active: dev
  datasource:
    old:
#        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/FirstDataBase?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver
    new:
#        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/SecondDataBase?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123
        driver-class-name: com.mysql.jdbc.Driver

  jpa:
      properties:
        hibernate:
          show_sql: true
          format_sql: true
server:
  port: 8888

#    oldDataBase:
#      jdbc-url: jdbc:mysql://localhost:3306/nationalOld?&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
#      username: root
#      password: zh94061011
